### ISSUE TITLE
Splash Screen version mismatch

### ISSUE THREAD

**Issue by vbz89** [FracktalWorks/Fracktory3#1]
**Describe the bug**
The splash screen version displayin 3.0b5 when the actual version is 3.0b8

**To Reproduce**
1. Go to 'Fracktory folder unzipped'
2. Click on 'Fracktory.exe'
3. Wait for splash screen.

**Expected behavior**
Expected correct version to be displayed.

**Screenshots**
![fracktory-splash](https://user-images.githubusercontent.com/29619546/71325209-7c65b980-250f-11ea-842c-6d0cbbe4a94a.png)

**Additional context**
C:\Users\~\Fracktory3-3.0_b8\resources\images

**Comment by ganeshmev** [comment]
**Describe the bug**
Version name change (manual)

**To change the version**
Steps to make the changes

1. Copy "python36" (Zip File) to any editable directory.
2. Find "CuraVersion" in \python36\cura. Open the file in an editor and use editor type as python.
3. Find the string you want to replace and make changes.
4. To make changes only take the CuraVersion file and make changes. _Extracting the python36 zip and again zipping breaks the operation. Always replace the CuraVersion_.

**Comment by vjvarada** [comment]
CuraVersion is  a *.pyc file, which is compiled. Doesn't have any access to strings. 

![image](https://user-images.githubusercontent.com/940424/71349056-0f483780-2594-11ea-864d-65e1b52e54cc.png)

**Comment by vbz89** [comment]
We already have a fix for this and the steps are mentioned by Ganesh. This has allowed us to change the version to 3.0b8 now in the "splash screen" and in the "About" option.


![Annotation 2019-12-23 163639](https://user-images.githubusercontent.com/29619546/71354589-6ce38080-25a2-11ea-8137-46b77b36d013.jpg)

**Comment by vjvarada** [comment]
Whoa, how does it look so much different than mine!

**Comment by vjvarada** [comment]
Can one of you commit with the new version set, ill push a new release.

**Comment by vbz89** [comment]
Closing this now that this change has been made.
