### ISSUE TITLE
Combing is "noskin" in all the printers. It needs to be "off". Only in Pro Dual its "off"

### ISSUE THREAD

**Issue by ganeshmev** [FracktalWorks/Fracktory3#3]
**Describe the bug**
Combing to be turned off

**Screenshots**
![image](https://user-images.githubusercontent.com/35722311/71340974-7eb32c80-257e-11ea-84d6-a4ebc5027ab9.png)

**Comment by vjvarada** [comment]
Check if you are using the correct Facktory, its already been changed.

![image](https://user-images.githubusercontent.com/940424/71348569-d3f93900-2592-11ea-9267-7c44e8653ce8.png)

![image](https://user-images.githubusercontent.com/940424/71348639-fa1ed900-2592-11ea-9011-e2506adbf2ae.png)

**Comment by vjvarada** [comment]
@vbz89 check if this is happening with you or is it local only to @ganeshmev . Make sure you are opening the correct fracktory

**Comment by vbz89** [comment]
@vjvarada I checked and the error is because of wrong version being checked by @ganeshmev . Github and downloaded b8 definitions are correct, combing is "off". Am closing this now.
